name: testing to deploy nodejs app on server
on:
  push:
    branches: [ main ]
  
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
      - name: Use Node.js
        run: |
          curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt install nodejs
          node -v
