name: testing to deploy nodejs app on server
on:
  push:
    branches: [ main ]
  
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
      - name: Use Node.js
        run: |
          curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
          source ~/.profile
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
          nvm install 16.15.1
